CREATE TABLE financial_loan (
    id BIGINT PRIMARY KEY,
    address_state VARCHAR(10),
    application_type VARCHAR(30),
    emp_length VARCHAR(20),
    emp_title VARCHAR(100),
    grade CHAR(1),
    home_ownership VARCHAR(20),
    issue_date DATE,
    last_credit_pull_date DATE,
    last_payment_date DATE,
    loan_status VARCHAR(50),
    next_payment_date DATE,
    member_id BIGINT,
    purpose VARCHAR(100),
    sub_grade VARCHAR(5),
    term VARCHAR(20),
    verification_status VARCHAR(30),
    annual_income NUMERIC(12,2),
    dti NUMERIC(6,4),
    installment NUMERIC(10,2),
    int_rate NUMERIC(6,4),
    loan_amount INT,
    total_acc INT,
    total_payment INT
);
